language: minimal
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get install ansible
  - sudo ansible-galaxy install -r requirements.yml

before_script:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
  - mkdir -p ~/.ssh/
  - cp id_rsa ~/.ssh/
  - chmod 0600 ~/.ssh/id_rsa
# - ssh-keyscan -H $TGPROXY_HOSTS >> ~/.ssh/known_hosts
# - chmod 0600 ~/.ssh/known_hosts
  
script:
  - ls ~/.ssh/
  - sudo ansible-playbook -i $TGPROXY_HOSTS, play-tgproxy.yml -e "proxy_secret=$TGPROXY_SECRET proxy_tag=$TGPROXY_TAG"