before_install:
  - sudo apt-get update
  - sudo apt-get install ansible

before_script:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
  - mkdir -p ~/.ssh/
  - cp id_rsa ~/.ssh/
  
script:
  - echo "hello world!"
  - ansible -v