---
- hosts: all
  remote_user: root
  tasks:
  
    - name: Up telegram proxy container
      docker_container:
        name: tgproxy
        image: telegrammessenger/proxy
        pull: yes
        restart_policy: always
        ports:
          - "443:443"
        env:
          SECRET: "{{ proxy_secret }}"
          TAG: "{{ proxy_tag }}"